import {Colors} from '../../constants/Colors';

export const styles: any = {
  container: {
    padding: 16,
    backgroundColor: Colors.white,
    borderRadius: 8,
    marginBottom: 16,
  },
  title: {
    fontSize: 18,
    marginBottom: 8,
  },
  card: {
    width: '100%',
  },
  previewContainer: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '12px',
  },
  addButton: {
    width: '28%',
    aspectRatio: '1',
    borderRadius: '8px',
    border: '2px dashed #888',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    cursor: 'pointer',
    color: '#888',
    fontSize: '48px',
    userSelect: 'none',
  },
  plusSign: {
    lineHeight: 1,
  },
  previewWrapper: {
    position: 'relative',
    width: '28%',
    aspectRatio: '1',
    borderRadius: '8px',
    overflow: 'hidden',
    border: '1px solid #ccc',
  },
  previewImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    display: 'block',
  },
  closeButton: {
    position: 'absolute',
    top: '4px',
    right: '4px',
    backgroundColor: 'rgba(0,0,0,0.5)',
    border: 'none',
    borderRadius: '50%',
    color: 'white',
    width: '24px',
    height: '24px',
    fontSize: '18px',
    cursor: 'pointer',
    lineHeight: '20px',
    padding: 0,
  },
  eyeButton: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    border: 'none',
    borderRadius: '50%',
    color: '#fff',
    width: 24,
    height: 24,
    fontSize: 14,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'background-color 0.2s',
  },
};