export interface IIconOption {
  arrow_right_thin?: string
  arrow_right?: string
  camera?: string
  cart?: string
  checklist_success?: string
  close?: string
  edit?: string
  exit?: string
  filter?: string
  flag_english?: string
  flag_indonesia?: string
  flash_off?: string
  flash_on?: string
  history_transaction?: string
  image_not_available: string
  information?: string
  langugage?: string
  list?: string
  love_empty?: string
  love_filled?: string
  more?: string
  printer?: string
  question?: string
  rotate?: string
  scan_qr?: string
  send?: string
  support?: string
  tax?: string
  terms_and_conditions?: string
  wallet?: string
}