import {Colors} from '../../../constants/Colors';
import { StyleMap } from '../../BottomSheet/BottomSheet.component.types';

export const cameraStyles: StyleMap = {
  overlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    height: '100vh',
    width: '100vw',
    backgroundColor: Colors.black,
    zIndex: 2000,
    overflow: 'hidden',
  },
  video: {
    width: '100vw',
    height: '100vh',
    objectFit: 'cover',
  },
  previewImage: {
    width: '100vw',
    height: '100vh',
    objectFit: 'cover',
  },
  closeButton: {
    position: 'absolute',
    top: 20,
    right: 20,
    fontSize: 24,
    backgroundColor: Colors.blackTransparent5,
    color: Colors.white,
    border: 'none',
    borderRadius: '50%',
    width: 36,
    height: 36,
    cursor: 'pointer',
    textAlign: 'center',
    lineHeight: '36px',
  },
  sendButtonContainer: {
    height: 70,
    width: 70,
    backgroundColor: Colors.white,
    border: 'none',
    borderRadius: 100,
    cursor: 'pointer',
    justifyContent: 'center',
    alignItems: 'center',
    boxShadow: `0 4px 10px ${Colors.blackTransparent3}`,
  },
  sendButton: {
    height: 28,
    width: 28,
    marginLeft: 6,
  },
  floatingBottomButtons: {
    position: 'absolute',
    bottom: 60,
    left: '50%',
    transform: 'translate(-50%, 0)',
  },
  floatingBottomRotateButtons: {
    position: 'absolute',
    bottom: 65,
    left: '85%',
    transform: 'translate(-50%, 0)',
  },
  captureButton: {
    height: 70,
    width: 70,
    backgroundColor: Colors.white,
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
  },
  innerButton: {
    height: 60,
    width: 60,
    backgroundColor: Colors.white,
    borderRadius: 100,
    border: `1px solid ${Colors.blackTransparent6}`,
    boxShadow: `0 4px 10px ${Colors.blackTransparent3}`,
    justifyContent: 'center',
    alignItems: 'center',
  },
  captureRotateButton: {
    height: 50,
    width: 50,
    backgroundColor: Colors.white,
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
  },
  rotateButton: {
    height: 22,
    width: 22,
  },
};