name: Auto Release & Publish to npm

on:
  push:
    branches:
      - master

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Release Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci

      - name: Configure git user
        run: |
          git config --global user.name "rahmatsaputra"
          git config --global user.email "rahmatsaputra@users.noreply.github.com"

      - name: Auto bump version
        run: npx standard-version
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Push new version & tags
        run: git push --follow-tags origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Build library (Rollup)
        run: npm run build

      - name: Configure npm auth
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_REGISTRY: "https://registry.npmjs.org/"
